version: '3.8'

services:
  web:
    build: .
    command: python3 run.py
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      database.env
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_volume:/var/lib/postgresql/data/

volumes:
  db_volume:
